# Generated by Django 4.1.1 on 2022-09-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_id',
        ),
    ]
